basePath: /
consumes:
    - application/json
info:
    description: '# Documentation ofr Product API'
    title: of Product API.
    version: 0.0.1
paths: {}
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
